version: '3.1'

services:
  rabbitmq_3_13:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_3_13
    #restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
