version: '3'
services:
  elasticsearch_7_9:
    image: wxmclub/elasticsearch-ext:7.9.3
    container_name: elasticsearch_7_9
    #restart: always
    networks:
      - netes7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - _JAVA_OPTIONS=-XX:UseSVE=0 #macOS 15.2 M4: Unable to launch Elasticsearch Docker container #118583 https://github.com/elastic/elasticsearch/issues/118583#issuecomment-2567270484
  kibana_7_9:
    image: kibana:7.9.3
    container_name: kibana_7_9
    #restart: always
    networks:
      - netes7
    depends_on:
      - elasticsearch_7_9
    links:
      - elasticsearch_7_9
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_7_9:9200
networks:
  netes7:
    driver: bridge
