version: '3'
services:
  es79:
    image: elasticsearch:7.9.3
    container_name: es79
    restart: always
    networks:
      - netes7
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana79:
    image: kibana:7.9.3
    container_name: kibana79
    restart: always
    networks:
      - netes7
    depends_on:
      - es79
    links:
      - es79
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es79:9200
networks:
  netes7:
    driver: bridge
