version: '3.1'

services:
  mysql_8_3:
    image: mysql:8.3
    container_name: mysql_8_3
    #restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - /data/docker/mysql_8_3/data:/var/lib/mysql
      - /data/docker/mysql_8_3/log:/var/log/mysql
