version: '3.1'

services:
  mysql_5_7:
    image: mysql:5.7
    container_name: mysql_5_7
    #restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - /data/docker/mysql_5_7/data:/var/lib/mysql
      - /data/docker/mysql_5_7/log:/var/log/mysql
